sudo: false
language: generic
compiler:
  - gcc
  - g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
  - make CC=gcc-6 CXX=g++-6
