name: linkedreads
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aquila=1.0.0
  - bam-readcount=0.8
  - bcftools=1.9
  - bedtools=2.26.0
  - bowtie2=2.3.4.3
  - bwa=0.7.17
  - fastp=0.12.4
  - flye=2.8.3
  - freebayes=1.3.2
  - gatk=3.6
  - hapcut2=1.2
  - jellyfish=2.2.10
  - megahit=1.2.9
  - metabat2=2.15
  - numpydoc=0.9.1
  - parallel=20230122
  - perl=5.26.2
  - picard=2.27.5
  - pigz=2.3.4
  - pip=23.0.1
  - python=3.7.4
  - pytorch=1.6.0
  - pytorch-cpu=1.1.0
  - pytorch-mutex=1.0
  - quickmerge=0.3
  - r-ade4=1.7_16
  - r-base=3.6.0
  - r-clustersim=0.49_1
  - r-factoextra=1.0.7
  - r-ggforce=0.3.2
  - r-ggplot2=3.2.1
  - r-proxy=0.4_24
  - r-vegan=2.5_6
  - samtools=1.9
  - scipy=1.3.1
  - seqtk=1.2
  - snakemake=5.5.4
  - sortedcontainers=2.1.0
  - spades=3.13.0
  - tabix=1.11
  - torchtext=0.7.0
  - torchvision=0.7.0
  - vcflib=1.0.0_rc3
  - vcftools=0.1.16
  - whatshap=1.0
  - zlib=1.2.11
  - pip:
    - numpy==1.16.1
    - pandas==1.3.5
    - pysam==0.16.0.1
    - rph-kmeans==1.0.0
    - scikit-learn==1.0.2
