name: linkedreads
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - aquila
  - bam-readcount
  - bcftools
  - bedtools
  - bowtie2
  - bwa
  - fastp
  - flye
  - freebayes
  - gatk=3.6
  - hapcut2
  - jellyfish
  - megahit
  - metabat2
  - numpydoc
  - parallel
  - picard
  - pigz
  - pip
  - python>=3.6
  - pytorch
  - pytorch-cpu
  - pytorch-mutex
  - quickmerge
  - r-ade4
  - r-base
  - r-clustersim
  - r-factoextra
  - r-ggforce
  - r-ggplot2
  - r-proxy
  - r-vegan
  - samtools
  - scipy
  - seqtk
  - snakemake
  - sortedcontainers
  - spades
  - tabix
  - torchtext
  - torchvision
  - vcflib
  - vcftools
  - whatshap
  - zlib
  - pip:
    - numpy
    - pandas
    - pysam
    - rph-kmeans
    - scikit-learn
